### ISSUE TITLE
Publish as a community provider in terraform registry

### ISSUE THREAD

**Issue by prodrigestivill** [awsiv/terraform-provider-rdsdataservice#1]
It would be great if you can publish it as a community provider in terraform registry:
https://registry.terraform.io/publish/provider

Thanks.

**Comment by awsiv** [comment]
> It would be great if you can publish it as a community provider in terraform registry:
> 
> https://registry.terraform.io/publish/provider


Will look into it thanks :)

**Comment by awsiv** [comment]
Provider published to terraform registry: https://registry.terraform.io/providers/awsiv/rdsdataservice/latest

Please give it a try :)
